# Generated by Django 5.1.1 on 2024-10-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Usuario Activo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin_negocio',
            field=models.BooleanField(default=False, verbose_name='Admin. de negocio'),
        ),
    ]
