# Generated by Django 5.1.1 on 2024-09-16 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_administrador_options_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='user_admin',
            new_name='nombre_admin',
        ),
    ]
