# Generated by Django 5.1.1 on 2024-10-17 02:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_remove_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'Solo se permiten letras y espacios.')]),
        ),
    ]
