# Generated by Django 5.1.1 on 2024-09-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_administrador_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
