# Generated by Django 5.1.1 on 2024-09-25 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Solo se permiten números en este campo', regex='^\\d+$')]),
        ),
    ]
