# Generated by Django 5.1.1 on 2024-10-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_cliente_nombre_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='rubro',
            field=models.CharField(choices=[('tienda', 'Tienda'), ('restaurante', 'Restaurante'), ('tecnologia', 'Tecnología'), ('moda', 'Moda'), ('automotriz', 'Automotriz'), ('LocalesNocturnos', 'Locales Nocturnos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin_negocio',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Admin. de negocio'),
        ),
    ]
