# Generated by Django 5.1.1 on 2024-10-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0009_alter_negocio_rubro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='rubro',
            field=models.CharField(choices=[('tienda', 'Tienda'), ('restaurante', 'Restaurante'), ('tecnologia', 'Tecnología'), ('moda', 'Moda'), ('discoteca', 'Discoteca')], max_length=20),
        ),
    ]
