# Generated by Django 5.1.1 on 2024-09-29 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geografia', '0001_initial'),
        ('perfil', '0013_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geografia.departamento'),
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='distrito',
            name='provincia',
        ),
        migrations.AlterField(
            model_name='administrador',
            name='distrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geografia.distrito'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geografia.provincia'),
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Distrito',
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
    ]
