# Generated by Django 5.1.1 on 2024-11-06 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.subcategoria'),
            preserve_default=False,
        ),
    ]
