# Generated by Django 5.1.1 on 2024-11-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tamaño',
            field=models.CharField(choices=[('GRANDE', 'Grande'), ('MEDIANO', 'Mediano'), ('MINI', 'Mini')], default=11, max_length=10),
            preserve_default=False,
        ),
    ]
